// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Cognito: typeof import('./components/Cognito.vue')['default']
    Colors: typeof import('./components/Colors.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Draggable: typeof import('./components/Draggable.vue')['default']
    Dropzone: typeof import('./components/Dropzone.vue')['default']
    Fetch: typeof import('./components/Fetch.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Todo: typeof import('./components/Todo.vue')['default']
  }
}

export {}
